name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.47.2'
          cache: true

      - name: Generate Android platform files
        run: flutter create --platforms=android --project-name morabi_yar .

      - name: Check Android files
        run: |
          echo "Android files:"
          find android -maxdepth 3 -type f | sort

      - name: Get packages
        run: flutter pub get

      - name: Remove generated sample test
        run: rm -rf test

      - name: Analyze
        run: flutter analyze
        continue-on-error: true

      - name: Build release APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: morabi-yar-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

